version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=smartmeterai
    networks:
      - smartmeterai

  smartmeterai:
    image: smartmeterai:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    networks:
      - smartmeterai

networks:
  smartmeterai:
    driver: bridge

  